spring.application.name=mindwell
#Configuración BD

spring.datasource.url=jdbc:mysql://localhost:3306/mindwell
spring.datasource.username=root
spring.datasource.password= 
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Configuraciones de JPA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Dialecto (Versión)

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect